{
 "title": "App Metrics (Custom)",
 "tags": [
  "apps",
  "python",
  "node",
  "redis"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Count by Endpoint",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Hit vs Miss (Rate)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_cache_hit_count_total[1m])) by (instance)",
     "legendFormat": "HIT {{instance}}"
    },
    {
     "expr": "sum(rate(app_cache_miss_count_total[1m])) by (instance)",
     "legendFormat": "MISS {{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency Histogram (p95)",
   "type": "heatmap",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}